# path to the xpcc root directory
xpccpath = '../../..'
# execute the common SConstruct file
execfile(xpccpath + '/scons/SConstruct')

binfile = env.Bin(program)

env.Alias('dfu', env.DfuStm32Programmer(binfile))
